site_name: Learning Lisp
site_author: 'zhoujiagen@gmail.com'
copyright: MIT
repo_name: learning-lisp
repo_url: https://github.com/zhoujiagen/learning-lisp

nav:
    - Home: index.md
    - Common Lisp:
      - 'Tools': common-lisp/tool.md
      - 'Terminology': common-lisp/terminology.md
      - '语言参考资源': common-lisp/spec.md
      - 'HyperSpec':
        - 'Index': common-lisp/HyperSpec/index.md
        - '1. 介绍': common-lisp/HyperSpec/01-Introduction.md
        - '2. 语法': common-lisp/HyperSpec/02-Syntax.md
        - '3. 求值和编译': common-lisp/HyperSpec/03-Evaluation-and-Compilation.md
        - '4. 类型和类': common-lisp/HyperSpec/04-Types-and-Classes.md
        - '5. 数据和控制流': common-lisp/HyperSpec/05-Data-and-Control-Flow.md
        - '6. 迭代': common-lisp/HyperSpec/06-Iteration.md
        - '7. 对象': common-lisp/HyperSpec/07-Objects.md
        - '8. 结构': common-lisp/HyperSpec/08-Structures.md
        - '9. 状况': common-lisp/HyperSpec/09-Conditions.md
        - '10. 符号': common-lisp/HyperSpec/10-Symbols.md
        - '11. 包': common-lisp/HyperSpec/11-Packages.md
        - '12. 数值': common-lisp/HyperSpec/12-Numbers.md
        - '13. 字符': common-lisp/HyperSpec/13-Characters.md
        - '14. Cons': common-lisp/HyperSpec/14-Conses.md
        - '15. 数组': common-lisp/HyperSpec/15-Arrays.md
        - '16. 字符串': common-lisp/HyperSpec/16-Strings.md
        - '17. 序列': common-lisp/HyperSpec/17-Sequences.md
        - '18. 哈希表': common-lisp/HyperSpec/18-Hash-Tables.md
        - '19. 文件名': common-lisp/HyperSpec/19-Filenames.md
        - '20. 文件': common-lisp/HyperSpec/20-Files.md
        - '21. 流': common-lisp/HyperSpec/21-Streams.md
        - '22. 打印器': common-lisp/HyperSpec/22-Printer.md
        - '23. 读取器': common-lisp/HyperSpec/23-Reader.md
        - '24. 系统构造': common-lisp/HyperSpec/24-System-Construction.md
        - '25. 环境': common-lisp/HyperSpec/25-Environment.md
        - '词汇表': common-lisp/HyperSpec/Glossary.md
        - '字典': common-lisp/HyperSpec/Dictionary.md
        - '978个符号': common-lisp/HyperSpec/Symbols.md
        - '图片索引': common-lisp/HyperSpec/Figures-index.md
    - Scheme:
      - 'Index': scheme/scheme.md
      - 'Chez Scheme Concepts': scheme/chez-concepts.md
      - 'Chez Scheme': scheme/chez.md


#theme: readthedocs
theme:
  name: material
extra:
  search:
    language: 'en'
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: False
  - toc:
      permalink: true
  - pymdownx.arithmatex # LaTeX math equations
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - markdown_inline_graphviz

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
